// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spectral_profile.proto

#include "spectral_profile.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_defs_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_defs_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_SpectralProfile;
}  // namespace protobuf_defs_2eproto
namespace CARTA {
class SpectralProfileDataDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SpectralProfileData>
      _instance;
} _SpectralProfileData_default_instance_;
}  // namespace CARTA
namespace protobuf_spectral_5fprofile_2eproto {
static void InitDefaultsSpectralProfileData() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::CARTA::_SpectralProfileData_default_instance_;
    new (ptr) ::CARTA::SpectralProfileData();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CARTA::SpectralProfileData::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_SpectralProfileData =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsSpectralProfileData}, {
      &protobuf_defs_2eproto::scc_info_SpectralProfile.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_SpectralProfileData.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CARTA::SpectralProfileData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CARTA::SpectralProfileData, file_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CARTA::SpectralProfileData, region_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CARTA::SpectralProfileData, stokes_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CARTA::SpectralProfileData, progress_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CARTA::SpectralProfileData, profiles_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::CARTA::SpectralProfileData)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::CARTA::_SpectralProfileData_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "spectral_profile.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\026spectral_profile.proto\022\005CARTA\032\ndefs.pr"
      "oto\"\205\001\n\023SpectralProfileData\022\017\n\007file_id\030\001"
      " \001(\017\022\021\n\tregion_id\030\002 \001(\017\022\016\n\006stokes\030\003 \001(\017\022"
      "\020\n\010progress\030\004 \001(\002\022(\n\010profiles\030\005 \003(\0132\026.CA"
      "RTA.SpectralProfileb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 187);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "spectral_profile.proto", &protobuf_RegisterTypes);
  ::protobuf_defs_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_spectral_5fprofile_2eproto
namespace CARTA {

// ===================================================================

void SpectralProfileData::InitAsDefaultInstance() {
}
void SpectralProfileData::clear_profiles() {
  profiles_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SpectralProfileData::kFileIdFieldNumber;
const int SpectralProfileData::kRegionIdFieldNumber;
const int SpectralProfileData::kStokesFieldNumber;
const int SpectralProfileData::kProgressFieldNumber;
const int SpectralProfileData::kProfilesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SpectralProfileData::SpectralProfileData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_spectral_5fprofile_2eproto::scc_info_SpectralProfileData.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:CARTA.SpectralProfileData)
}
SpectralProfileData::SpectralProfileData(const SpectralProfileData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      profiles_(from.profiles_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&file_id_, &from.file_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&progress_) -
    reinterpret_cast<char*>(&file_id_)) + sizeof(progress_));
  // @@protoc_insertion_point(copy_constructor:CARTA.SpectralProfileData)
}

void SpectralProfileData::SharedCtor() {
  ::memset(&file_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&progress_) -
      reinterpret_cast<char*>(&file_id_)) + sizeof(progress_));
}

SpectralProfileData::~SpectralProfileData() {
  // @@protoc_insertion_point(destructor:CARTA.SpectralProfileData)
  SharedDtor();
}

void SpectralProfileData::SharedDtor() {
}

void SpectralProfileData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SpectralProfileData::descriptor() {
  ::protobuf_spectral_5fprofile_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_spectral_5fprofile_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SpectralProfileData& SpectralProfileData::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_spectral_5fprofile_2eproto::scc_info_SpectralProfileData.base);
  return *internal_default_instance();
}


void SpectralProfileData::Clear() {
// @@protoc_insertion_point(message_clear_start:CARTA.SpectralProfileData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  profiles_.Clear();
  ::memset(&file_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&progress_) -
      reinterpret_cast<char*>(&file_id_)) + sizeof(progress_));
  _internal_metadata_.Clear();
}

bool SpectralProfileData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CARTA.SpectralProfileData)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // sfixed32 file_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &file_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sfixed32 region_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &region_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sfixed32 stokes = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(29u /* 29 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &stokes_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float progress = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(37u /* 37 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &progress_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .CARTA.SpectralProfile profiles = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_profiles()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CARTA.SpectralProfileData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CARTA.SpectralProfileData)
  return false;
#undef DO_
}

void SpectralProfileData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CARTA.SpectralProfileData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // sfixed32 file_id = 1;
  if (this->file_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(1, this->file_id(), output);
  }

  // sfixed32 region_id = 2;
  if (this->region_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(2, this->region_id(), output);
  }

  // sfixed32 stokes = 3;
  if (this->stokes() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(3, this->stokes(), output);
  }

  // float progress = 4;
  if (this->progress() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->progress(), output);
  }

  // repeated .CARTA.SpectralProfile profiles = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->profiles_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5,
      this->profiles(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:CARTA.SpectralProfileData)
}

::google::protobuf::uint8* SpectralProfileData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:CARTA.SpectralProfileData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // sfixed32 file_id = 1;
  if (this->file_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(1, this->file_id(), target);
  }

  // sfixed32 region_id = 2;
  if (this->region_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(2, this->region_id(), target);
  }

  // sfixed32 stokes = 3;
  if (this->stokes() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(3, this->stokes(), target);
  }

  // float progress = 4;
  if (this->progress() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->progress(), target);
  }

  // repeated .CARTA.SpectralProfile profiles = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->profiles_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->profiles(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CARTA.SpectralProfileData)
  return target;
}

size_t SpectralProfileData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CARTA.SpectralProfileData)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .CARTA.SpectralProfile profiles = 5;
  {
    unsigned int count = static_cast<unsigned int>(this->profiles_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->profiles(static_cast<int>(i)));
    }
  }

  // sfixed32 file_id = 1;
  if (this->file_id() != 0) {
    total_size += 1 + 4;
  }

  // sfixed32 region_id = 2;
  if (this->region_id() != 0) {
    total_size += 1 + 4;
  }

  // sfixed32 stokes = 3;
  if (this->stokes() != 0) {
    total_size += 1 + 4;
  }

  // float progress = 4;
  if (this->progress() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SpectralProfileData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CARTA.SpectralProfileData)
  GOOGLE_DCHECK_NE(&from, this);
  const SpectralProfileData* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SpectralProfileData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CARTA.SpectralProfileData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CARTA.SpectralProfileData)
    MergeFrom(*source);
  }
}

void SpectralProfileData::MergeFrom(const SpectralProfileData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CARTA.SpectralProfileData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  profiles_.MergeFrom(from.profiles_);
  if (from.file_id() != 0) {
    set_file_id(from.file_id());
  }
  if (from.region_id() != 0) {
    set_region_id(from.region_id());
  }
  if (from.stokes() != 0) {
    set_stokes(from.stokes());
  }
  if (from.progress() != 0) {
    set_progress(from.progress());
  }
}

void SpectralProfileData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CARTA.SpectralProfileData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SpectralProfileData::CopyFrom(const SpectralProfileData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CARTA.SpectralProfileData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SpectralProfileData::IsInitialized() const {
  return true;
}

void SpectralProfileData::Swap(SpectralProfileData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SpectralProfileData::InternalSwap(SpectralProfileData* other) {
  using std::swap;
  CastToBase(&profiles_)->InternalSwap(CastToBase(&other->profiles_));
  swap(file_id_, other->file_id_);
  swap(region_id_, other->region_id_);
  swap(stokes_, other->stokes_);
  swap(progress_, other->progress_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SpectralProfileData::GetMetadata() const {
  protobuf_spectral_5fprofile_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_spectral_5fprofile_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace CARTA
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::CARTA::SpectralProfileData* Arena::CreateMaybeMessage< ::CARTA::SpectralProfileData >(Arena* arena) {
  return Arena::CreateInternal< ::CARTA::SpectralProfileData >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
