// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stop_moment_calc.proto

#ifndef PROTOBUF_INCLUDED_stop_5fmoment_5fcalc_2eproto
#define PROTOBUF_INCLUDED_stop_5fmoment_5fcalc_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_stop_5fmoment_5fcalc_2eproto 

namespace protobuf_stop_5fmoment_5fcalc_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_stop_5fmoment_5fcalc_2eproto
namespace CARTA {
class StopMomentCalc;
class StopMomentCalcDefaultTypeInternal;
extern StopMomentCalcDefaultTypeInternal _StopMomentCalc_default_instance_;
}  // namespace CARTA
namespace google {
namespace protobuf {
template<> ::CARTA::StopMomentCalc* Arena::CreateMaybeMessage<::CARTA::StopMomentCalc>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace CARTA {

// ===================================================================

class StopMomentCalc : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CARTA.StopMomentCalc) */ {
 public:
  StopMomentCalc();
  virtual ~StopMomentCalc();

  StopMomentCalc(const StopMomentCalc& from);

  inline StopMomentCalc& operator=(const StopMomentCalc& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StopMomentCalc(StopMomentCalc&& from) noexcept
    : StopMomentCalc() {
    *this = ::std::move(from);
  }

  inline StopMomentCalc& operator=(StopMomentCalc&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const StopMomentCalc& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StopMomentCalc* internal_default_instance() {
    return reinterpret_cast<const StopMomentCalc*>(
               &_StopMomentCalc_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(StopMomentCalc* other);
  friend void swap(StopMomentCalc& a, StopMomentCalc& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StopMomentCalc* New() const final {
    return CreateMaybeMessage<StopMomentCalc>(NULL);
  }

  StopMomentCalc* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<StopMomentCalc>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const StopMomentCalc& from);
  void MergeFrom(const StopMomentCalc& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StopMomentCalc* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // sfixed32 file_id = 1;
  void clear_file_id();
  static const int kFileIdFieldNumber = 1;
  ::google::protobuf::int32 file_id() const;
  void set_file_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CARTA.StopMomentCalc)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 file_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_stop_5fmoment_5fcalc_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StopMomentCalc

// sfixed32 file_id = 1;
inline void StopMomentCalc::clear_file_id() {
  file_id_ = 0;
}
inline ::google::protobuf::int32 StopMomentCalc::file_id() const {
  // @@protoc_insertion_point(field_get:CARTA.StopMomentCalc.file_id)
  return file_id_;
}
inline void StopMomentCalc::set_file_id(::google::protobuf::int32 value) {
  
  file_id_ = value;
  // @@protoc_insertion_point(field_set:CARTA.StopMomentCalc.file_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace CARTA

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_stop_5fmoment_5fcalc_2eproto
