// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: region_stats.proto

#include "region_stats.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_defs_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_defs_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_StatisticsValue;
}  // namespace protobuf_defs_2eproto
namespace CARTA {
class RegionStatsDataDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<RegionStatsData>
      _instance;
} _RegionStatsData_default_instance_;
}  // namespace CARTA
namespace protobuf_region_5fstats_2eproto {
static void InitDefaultsRegionStatsData() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::CARTA::_RegionStatsData_default_instance_;
    new (ptr) ::CARTA::RegionStatsData();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CARTA::RegionStatsData::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_RegionStatsData =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsRegionStatsData}, {
      &protobuf_defs_2eproto::scc_info_StatisticsValue.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_RegionStatsData.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CARTA::RegionStatsData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CARTA::RegionStatsData, file_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CARTA::RegionStatsData, region_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CARTA::RegionStatsData, channel_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CARTA::RegionStatsData, stokes_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CARTA::RegionStatsData, statistics_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::CARTA::RegionStatsData)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::CARTA::_RegionStatsData_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "region_stats.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\022region_stats.proto\022\005CARTA\032\ndefs.proto\""
      "\202\001\n\017RegionStatsData\022\017\n\007file_id\030\001 \001(\017\022\021\n\t"
      "region_id\030\002 \001(\017\022\017\n\007channel\030\003 \001(\017\022\016\n\006stok"
      "es\030\004 \001(\017\022*\n\nstatistics\030\005 \003(\0132\026.CARTA.Sta"
      "tisticsValueb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 180);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "region_stats.proto", &protobuf_RegisterTypes);
  ::protobuf_defs_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_region_5fstats_2eproto
namespace CARTA {

// ===================================================================

void RegionStatsData::InitAsDefaultInstance() {
}
void RegionStatsData::clear_statistics() {
  statistics_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RegionStatsData::kFileIdFieldNumber;
const int RegionStatsData::kRegionIdFieldNumber;
const int RegionStatsData::kChannelFieldNumber;
const int RegionStatsData::kStokesFieldNumber;
const int RegionStatsData::kStatisticsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RegionStatsData::RegionStatsData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_region_5fstats_2eproto::scc_info_RegionStatsData.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:CARTA.RegionStatsData)
}
RegionStatsData::RegionStatsData(const RegionStatsData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      statistics_(from.statistics_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&file_id_, &from.file_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&stokes_) -
    reinterpret_cast<char*>(&file_id_)) + sizeof(stokes_));
  // @@protoc_insertion_point(copy_constructor:CARTA.RegionStatsData)
}

void RegionStatsData::SharedCtor() {
  ::memset(&file_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&stokes_) -
      reinterpret_cast<char*>(&file_id_)) + sizeof(stokes_));
}

RegionStatsData::~RegionStatsData() {
  // @@protoc_insertion_point(destructor:CARTA.RegionStatsData)
  SharedDtor();
}

void RegionStatsData::SharedDtor() {
}

void RegionStatsData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* RegionStatsData::descriptor() {
  ::protobuf_region_5fstats_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_region_5fstats_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const RegionStatsData& RegionStatsData::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_region_5fstats_2eproto::scc_info_RegionStatsData.base);
  return *internal_default_instance();
}


void RegionStatsData::Clear() {
// @@protoc_insertion_point(message_clear_start:CARTA.RegionStatsData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  statistics_.Clear();
  ::memset(&file_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&stokes_) -
      reinterpret_cast<char*>(&file_id_)) + sizeof(stokes_));
  _internal_metadata_.Clear();
}

bool RegionStatsData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CARTA.RegionStatsData)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // sfixed32 file_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &file_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sfixed32 region_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &region_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sfixed32 channel = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(29u /* 29 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &channel_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sfixed32 stokes = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(37u /* 37 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &stokes_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .CARTA.StatisticsValue statistics = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_statistics()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CARTA.RegionStatsData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CARTA.RegionStatsData)
  return false;
#undef DO_
}

void RegionStatsData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CARTA.RegionStatsData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // sfixed32 file_id = 1;
  if (this->file_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(1, this->file_id(), output);
  }

  // sfixed32 region_id = 2;
  if (this->region_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(2, this->region_id(), output);
  }

  // sfixed32 channel = 3;
  if (this->channel() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(3, this->channel(), output);
  }

  // sfixed32 stokes = 4;
  if (this->stokes() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(4, this->stokes(), output);
  }

  // repeated .CARTA.StatisticsValue statistics = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->statistics_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5,
      this->statistics(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:CARTA.RegionStatsData)
}

::google::protobuf::uint8* RegionStatsData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:CARTA.RegionStatsData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // sfixed32 file_id = 1;
  if (this->file_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(1, this->file_id(), target);
  }

  // sfixed32 region_id = 2;
  if (this->region_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(2, this->region_id(), target);
  }

  // sfixed32 channel = 3;
  if (this->channel() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(3, this->channel(), target);
  }

  // sfixed32 stokes = 4;
  if (this->stokes() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(4, this->stokes(), target);
  }

  // repeated .CARTA.StatisticsValue statistics = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->statistics_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->statistics(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CARTA.RegionStatsData)
  return target;
}

size_t RegionStatsData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CARTA.RegionStatsData)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .CARTA.StatisticsValue statistics = 5;
  {
    unsigned int count = static_cast<unsigned int>(this->statistics_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->statistics(static_cast<int>(i)));
    }
  }

  // sfixed32 file_id = 1;
  if (this->file_id() != 0) {
    total_size += 1 + 4;
  }

  // sfixed32 region_id = 2;
  if (this->region_id() != 0) {
    total_size += 1 + 4;
  }

  // sfixed32 channel = 3;
  if (this->channel() != 0) {
    total_size += 1 + 4;
  }

  // sfixed32 stokes = 4;
  if (this->stokes() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RegionStatsData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CARTA.RegionStatsData)
  GOOGLE_DCHECK_NE(&from, this);
  const RegionStatsData* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const RegionStatsData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CARTA.RegionStatsData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CARTA.RegionStatsData)
    MergeFrom(*source);
  }
}

void RegionStatsData::MergeFrom(const RegionStatsData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CARTA.RegionStatsData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  statistics_.MergeFrom(from.statistics_);
  if (from.file_id() != 0) {
    set_file_id(from.file_id());
  }
  if (from.region_id() != 0) {
    set_region_id(from.region_id());
  }
  if (from.channel() != 0) {
    set_channel(from.channel());
  }
  if (from.stokes() != 0) {
    set_stokes(from.stokes());
  }
}

void RegionStatsData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CARTA.RegionStatsData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RegionStatsData::CopyFrom(const RegionStatsData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CARTA.RegionStatsData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RegionStatsData::IsInitialized() const {
  return true;
}

void RegionStatsData::Swap(RegionStatsData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RegionStatsData::InternalSwap(RegionStatsData* other) {
  using std::swap;
  CastToBase(&statistics_)->InternalSwap(CastToBase(&other->statistics_));
  swap(file_id_, other->file_id_);
  swap(region_id_, other->region_id_);
  swap(channel_, other->channel_);
  swap(stokes_, other->stokes_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata RegionStatsData::GetMetadata() const {
  protobuf_region_5fstats_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_region_5fstats_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace CARTA
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::CARTA::RegionStatsData* Arena::CreateMaybeMessage< ::CARTA::RegionStatsData >(Arena* arena) {
  return Arena::CreateInternal< ::CARTA::RegionStatsData >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
